In [8]:
from qutip import *
import numpy as np

In [2]:
vac = basis(5,0)

In [3]:
a = destroy(5)

In [4]:
a

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]

In [6]:
vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [7]:
a*vac

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]

# 真空态
这么来看的话，basis(M,0)就是真空态，但是为什么在计算能量的时候，就是对不上了呢？<p>现在感觉应该不是充电时间的问题，到底是哪里出了问题了呢？充电时间的话，无论是大还是小，最终的结果都没有影响

In [13]:
N = 5
z = np.arcsinh(np.sqrt(N))
s = squeeze(N,z)
vac = basis(N,0)
psi = s*vac

In [14]:
psi

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.71880225]
 [ 0.        ]
 [-0.09428823]
 [ 0.        ]
 [ 0.68879101]]